version: '3'
services:
  forwarder:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: /home/ubuntu/SubdomainForwarder/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ../TestServer/Server/static/:/static
    depends_on:
      - tbserver
      - survey
      - web

  tbserver:
    build:
      context: ../TestServer/Server/
      dockerfile: Dockerfile
    command: >
      sh -c " python manage.py collectstatic --no-input &&
              daphne -b 0.0.0.0 -p 8000 TBserver.asgi:application"
    volumes: 
      - ../TestServer/Server/static/:/source/TBserver/.static_root
    expose:
      - '8000'


  survey:
    build:
      context: ../SurveyServer/hackaton-server/
      dockerfile: Dockerfile
    command: >
      sh -c " python run.py"
    volumes:
      - ../SurveyServer/hackaton-server/:/source/my.db
    expose:
      - '8080'

  web:
    build:
      context: ../hackathon_frontend/
      dockerfile: Dockerfile
    expose:
      - '3000'    
  
        

